- sparkconfig:
    appname: "ELBLogProcessing"
    shufflepartitions: 5
    sessiontimezone: "UTC"
- FilePaths:
    inputfilepath: "data/log_sample.log.gz"
    sessiontableoutput: "output/tables/sessiontable"
    sessionaggoutput: "output/tables/sessionagg"
    sessionstatsoutput: "output/tables/sessionstats"
    osaggoutput: "output/tables/osagg"
    deviceaggoutput: "output/tables/deviceagg"
    browseraggoutput: "output/tables/browseragg"
    ipminmaxstatsoutput: "output/tables/ipminmaxstats"
    minmaxavgoutput: "output/tables/minmaxavgoutput"
    sessiontablehashoutput: "output/tables/sessionipagg"
    sessiontableoutputcsv: "output/tables/sessiontablecsv"
    sessionaggoutputcsv: "output/tables/sessionaggcsv"
    sessionstatsoutputcsv: "output/tables/sessionstatscsv"
    osaggoutputcsv: "output/tables/osaggcsv"
    deviceaggoutputcsv: "output/tables/deviceaggcsv"
    browseraggoutputcsv: "output/tables/browseraggcsv"
    ipminmaxstatsoutputcsv: "output/tables/ipminmaxstatscsv"
    minmaxavgoutputcsv: "output/tables/minmaxavgoutputcsv"
    sessiontablehashoutputcsv: "output/tables/sessionipaggcsv"
